### ISSUE TITLE
🏗️ Convert Token Server to Rust (meta)

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/tokenserver#177]
The token server should be ported to rust. This issue will encapsulate the requirements and act as a cornerstone for that effort.

In addition, the token server will probably be rolled into an existing service like syncstorage-rs, so it's important to isolate functions and interfaces so that they can be brought in as seamlessly as possible.

Note: while mozilla production will switch to using spanner as it's backend, there are a host of providers that will continue to need SQL database support. The current database system they're using is MySQL. 

To aid in that effort the following structures will be required:

* rust stable (not nightly) with async/await support
* meet or exceed [foxsec baseline criteria](https://github.com/mozilla-services/websec-check): 
  * [failure](https://crates.io/crates/failure) error handling
  * slog / moz-slog error reporting
  * pass `cargo format` and `cargo clippy` without warnings or errors
* [Actix-web 2.0+](https://github.com/actix/actix-web) webserver framework
* [diesel ](https://diesel.rs/)database framework

various core elements required are:

- [ ] **Assignment**: provide a means to persistently assign users to a valid node (allowing for node removal or rebalancing)
- [ ] **BrowserID verification**: provide auth token validation for BrowserID
- [ ] **OAuth verification**: provide auth token validation for OAuth
- [ ] **Dockerflow**: provide [dockerflow endpoints](https://github.com/mozilla-services/Dockerflow)
- [ ] Data storage for
  - [ ] Memory
  - [ ] SQL storage
- [ ] Misc. support functions including:
  - [ ] email hashing
  - [ ] fxa_metric hashing
  - [ ] timestamp normalization (to milisecond)
  - [ ] fxa_keyid generation and parsing

As well as the general functions required for the stand alone system
- [ ] JWT parser/compiler
- [ ] logging (using slog)
- [ ] metrics (using cadence)
- [ ] settings parser and management
- [ ] error handling (using failure)

All components need to pass appropriate unit and interactive testing.
